# ------------------------------------
#   官方手册: https://manual.serverless-devs.com/user-guide/aliyun/#fc3
#   有问题快来钉钉群问一下吧：33947367
# ------------------------------------

edition: 3.0.0
name: nginx-app
access: "default"
vars:
  region: "cn-shanghai"
  functionName: "zero-antd-admin"
resources:
  start_nginx:
    component: fc3
    props:
      region: ${vars.region}
      description: Serverless Devs Web Framework Function
      runtime: custom.debian10
      layers:
        - acs:fc:${vars.region}:official:layers/Nginx/versions/1
      timeout: 60
      cpu: 0.5
      memorySize: 512
      diskSize: 512
      instanceConcurrency: 100
      customRuntimeConfig:
        command:
          - "/opt/bin/nginx"
          - "-c"
          - "/code/nginx.conf"
          - "-g"
          - "daemon off;"
        port: 9000
      functionName: ${vars.functionName}
      code: ./dist
      triggers:
        - triggerName: httpTrigger
          triggerType: http
          triggerConfig:
            methods:
              - GET
              - POST
              - PUT
              - DELETE
            authType: anonymous
  fc3_domain_0:
    component: fc3-domain
    props:
      region: ${vars.region}
      domainName: auto
      protocol: HTTP
      routeConfig:
        routes:
          - path: /*
            functionName: ${vars.functionName}
