name: Deploy to ECS

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm i

      - name: Build project
        run: npm run build

        # 添加清理目标目录的步骤（在复制前执行）
      - name: Clean target directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ECS_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 判断部署目录是否存在
            if [ -d "${{ secrets.DEPLOY_PATH }}" ]; then
              # 进入部署目录
              cd ${{ secrets.DEPLOY_PATH }}
              # 直接清空目录中的所有内容
              rm -rf ./* ./.[!.]*
              echo "目标目录已完全清空"
            else
              echo "部署目录不存在，将创建目录"
              mkdir -p ${{ secrets.DEPLOY_PATH }}
            fi

      # 添加复制dist到ECS服务器的步骤
      - name: Copy dist to ECS server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.ECS_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/*"
          target: "${{ secrets.DEPLOY_PATH }}"
          strip_components: 1